// Advanced mode's TypeScript view: generate a standalone MCP-SDK server
// skeleton from the current graph doc. Deliberately a STARTING POINT for
// developers who outgrow the canvas — the generated file compiles against
// @modelcontextprotocol/sdk but is meant to be copied out and owned by the
// user, not round-tripped (JSON stays the single source of truth; the build
// plan's phase-4 compiler will own real emit).

import { reachableExecutionNodeIds, type GraphDoc, type ToolNode } from "@mcpeasy/schema";

function chainFor(doc: GraphDoc, tool: ToolNode): string[] {
  return reachableExecutionNodeIds(doc, tool.entry);
}

function tsString(value: string): string {
  return JSON.stringify(value);
}

/** One inputSchema property line per input, mirroring toolInputJsonSchema. */
function schemaProps(tool: ToolNode): string {
  return tool.inputs
    .map((i) => {
      const base =
        i.type === "enum"
          ? `{ type: "string", enum: ${JSON.stringify(i.enumValues ?? [])} }`
          : `{ type: ${tsString(i.type)} }`;
      return `        ${JSON.stringify(i.name)}: ${base},`;
    })
    .join("\n");
}

function stepComment(doc: GraphDoc, id: string): string {
  const node = doc.nodes[id];
  if (!node) return `      // ${id} (missing node)`;
  switch (node.kind) {
    case "action":
      return `      // ${id}: ${node.http.method} ${node.http.url || "(url not set)"}\n      // -> fetch(...) with the {{...}} templates resolved from args/env/prev`;
    case "command":
      return `      // ${id}: run executable ${tsString(node.command.executable)} with argv ${JSON.stringify(node.command.args)}`;
    case "script":
      return `      // ${id}: run ${node.script.runtime} script ${tsString(node.script.path)}`;
    case "code":
      return `      // ${id}: run trusted inline JavaScript in a bounded child process`;
    case "parallel":
      return `      // ${id}: Promise.all ${JSON.stringify(node.branches.map((branch) => branch.name))}, then join by branch name`;
    case "transform":
      return node.op === "pick"
        ? `      // ${id}: pick ${JSON.stringify(node.pick ?? [])} from the previous result`
        : `      // ${id}: render template ${tsString(node.template ?? "")}`;
    case "return":
      return `      // ${id}: return as ${node.format}`;
    default:
      return `      // ${id}`;
  }
}

/**
 * Generate the TypeScript SDK example for the doc. Uses the same low-level
 * Server + setRequestHandler seam as the real engine (buildServer.ts) so the
 * example teaches the pattern the project itself relies on.
 */
export function generateTypescript(doc: GraphDoc): string {
  const tools = Object.entries(doc.nodes).filter((e): e is [string, ToolNode] => e[1].kind === "tool");
  const toolBlocks = tools
    .map(([id, tool]) => {
      const steps = chainFor(doc, tool);
      const stepLines = steps.length
        ? steps.map((s) => stepComment(doc, s)).join("\n")
        : "      // (no chain wired yet, connect blocks on the canvas)";
      return `    {
      name: ${tsString(tool.name || id)},
      description: ${tsString(tool.description)},
      inputSchema: {
        type: "object",
        properties: {
${schemaProps(tool) || "          // (no inputs declared)"}
        },
        required: ${JSON.stringify(tool.inputs.filter((i) => i.required !== false).map((i) => i.name))},
      },
      // chain (executed by the engine at runtime):
${stepLines}
    },`;
    })
    .join("\n");

  return `// ${doc.server.name}, generated by MCPeasy (Advanced mode)${doc.server.creator ? `\n// Creator: ${doc.server.creator}` : ""}${doc.server.description ? `\n// ${doc.server.description.replace(/\r?\n/g, " ")}` : ""}
// A standalone MCP server skeleton over the official SDK. The canvas JSON
// stays the source of truth; use this to eject into hand-written code, or
// just to see what your graph means in SDK terms.
//
//   npm i @modelcontextprotocol/sdk
//   npx tsx server.ts   (serves over stdio, e.g. for Claude Desktop)

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

const server = new Server(
  { name: ${tsString(doc.server.name)}, version: ${tsString(doc.server.version)} },
  { capabilities: { tools: {} } },
);

// Env this server expects at startup:${doc.server.env.length ? doc.server.env.map((n) => `\n//   ${n}`).join("") : " (none declared)"}

server.setRequestHandler(ListToolsRequestSchema, () => ({
  tools: [
${toolBlocks || "    // (no tool blocks on the canvas yet)"}
  ],
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  // TODO: implement each tool's chain here (the comments above sketch the
  // steps the canvas currently wires). Throw McpError for protocol errors;
  // return { isError: true, content: [...] } for tool failures.
  return { content: [{ type: "text", text: "not implemented yet" }] };
});

await server.connect(new StdioServerTransport());
`;
}
